// JsFromRoutes CacheKey ca133e202a9e4a4870e36d4b206a402c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as usersSessions } from './Users/SessionsApi'
export { default as inertiaExample } from './InertiaExampleApi'
export { default as railsHealth } from './Rails/HealthApi'
export { default as pages } from './PagesApi'
export { default as users } from './UsersApi'
export { default as usersPosts } from './Users/PostsApi'
