// JsFromRoutes CacheKey 94f3118272a1c02b22fd9543401c54f3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/inertia-example'),
}
