// JsFromRoutes CacheKey 516f31889a827ffe71938658ca96b290
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  home: /* #__PURE__ */ definePathHelper('get', '/'),
}
