// JsFromRoutes CacheKey bac364c3176baa7ce4300d737c86632f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/users/signup'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/signup'),
  show: /* #__PURE__ */ definePathHelper('get', '/users'),
}
