// JsFromRoutes CacheKey 682e52581c6a1f46d52cda3ea29ec2fc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users/posts'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/posts'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/posts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/users/posts/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/posts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/posts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/posts/:id'),
}
